defaults:
  labels: ["triage"]
  body: |
    ## Description

    ## Details

templates:
  docs:
    labels: ["documentation"]
    title_prefix: "[Docs QC] "
    body: |
      ## Documentation Update

      ## What needs to be documented?

  chore:
    labels: ["chore"]
    title_prefix: "[Chore QC] "
    body: |
      ## Task

      ## Why is this needed?
