name: Task
description: A general task or todo item
labels: [task]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How do we know it's done?
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
